# Generated by Django 3.2 on 2021-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_apiurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrittendigit',
            name='correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handwrittendigit',
            name='imageDisplay',
            field=models.ImageField(default=False, upload_to=''),
            preserve_default=False,
        ),
    ]
