# Generated by Django 3.2 on 2021-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210424_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwrittendigit',
            name='imageDisplay',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
