# Generated by Django 3.2 on 2021-04-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_handwrittendigit_imagedisplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwrittendigit',
            name='imageDisplay',
            field=models.ImageField(default=False, upload_to=''),
            preserve_default=False,
        ),
    ]
