# Generated by Django 3.2 on 2021-04-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_handwrittendigit_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handwrittendigit',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='handwrittendigit',
            name='imageDisplay',
        ),
    ]
