# Generated by Django 3.2 on 2021-04-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_handwrittendigit_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrittendigit',
            name='imageDisplay',
            field=models.ImageField(default=False, upload_to=''),
            preserve_default=False,
        ),
    ]
