# Generated by Django 3.2 on 2021-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_handwrittendigit_imagedisplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiurl',
            name='serverOnline',
            field=models.BooleanField(default=False),
        ),
    ]
