# Generated by Django 3.2 on 2021-04-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_apiurl_serveronline'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrittendigit',
            name='guessReturned',
            field=models.BooleanField(default=False),
        ),
    ]
