# Generated by Django 3.2 on 2021-04-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_handwrittendigit_guessreturned'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrittendigit',
            name='guessVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='handwrittendigit',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
