# Generated by Django 4.0.1 on 2022-01-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20210427_0955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiUrl',
        ),
        migrations.DeleteModel(
            name='HandWrittenDigit',
        ),
    ]
